In [9]:
import numpy as np
import pandas as pd

In [10]:
data = pd.read_csv('Smartphone_Usage_Productivity_Dataset_50000.csv')

In [11]:
data.head()

,User_ID,Age,Gender,Occupation,Device_Type,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours
0,U1,58,Male,Professional,Android,1.3,6.7,6,8.8,4,42,1,8.7
1,U2,25,Male,Professional,Android,1.2,1.5,5,6.4,1,51,3,5.1
2,U3,19,Male,Student,iOS,5.3,5.7,5,9.0,4,14,5,6.3
3,U4,35,Female,Business Owner,iOS,5.8,2.5,2,5.7,3,36,6,12.8
4,U5,33,Male,Freelancer,Android,7.9,1.3,4,5.7,3,37,5,9.9

In [12]:
from sklearn.preprocessing import LabelEncoder

In [13]:
encoder = LabelEncoder()

In [16]:
encoder_Gender = LabelEncoder()
encoder_Occupation = LabelEncoder()
encoder_Device_Type = LabelEncoder()



data['Genderr'] = encoder_Gender.fit_transform(data['Gender'])

data['Occupation'] = encoder_Occupation.fit_transform(data['Occupation'])

data['Device_Type'] = encoder_Device_Type.fit_transform(data['Device_Type'])

In [15]:
print(encoder_Gender.classes_,encoder_Gender.transform(encoder_Gender.classes_))
print(encoder_Occupation.classes_,encoder_Occupation.transform(encoder_Occupation.classes_))
print(encoder_Device_Type.classes_,encoder_Device_Type.transform(encoder_Device_Type.classes_))

['Female' 'Male' 'Other'] [0 1 2]
['Business Owner' 'Freelancer' 'Professional' 'Student'] [0 1 2 3]
['Android' 'iOS'] [0 1]

In [17]:
data.head()

,User_ID,Age,Gender,Occupation,Device_Type,Daily_Phone_Hours,Social_Media_Hours,Work_Productivity_Score,Sleep_Hours,Stress_Level,App_Usage_Count,Caffeine_Intake_Cups,Weekend_Screen_Time_Hours,Genderr
0,U1,58,Male,2,0,1.3,6.7,6,8.8,4,42,1,8.7,1
1,U2,25,Male,2,0,1.2,1.5,5,6.4,1,51,3,5.1,1
2,U3,19,Male,3,1,5.3,5.7,5,9.0,4,14,5,6.3,1
3,U4,35,Female,0,1,5.8,2.5,2,5.7,3,36,6,12.8,0
4,U5,33,Male,1,0,7.9,1.3,4,5.7,3,37,5,9.9,1

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [25]:
X = data.drop(columns=['Stress_Level','User_ID'])
Y = data['Stress_Level']

In [26]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2)

In [27]:
model = LogisticRegression(max_iter=10000)

In [29]:
model.fit(X_train.drop(columns=['Gender']),Y_train)

LogisticRegression(max_iter=10000)

In [ ]:
Y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
acc = accuracy_score(Y_test,Y_pred)
print(acc)

#downlaod model ที่สร้างไว้

In [ ]:
import pickle

In [ ]:
filename = 'loan_model.sav'
pickle.dump(model,open(filename,'wb'))

#นํา file model มาใช้งาน

In [ ]:
loan_model = pickle.load(open('loan_model.sav','rb'))

In [ ]:
input_data = ([[22.0,0,4,71948.0,0,3,35000.0,4,16.02,0.49,3.0,561,0]])

prediction = loan_model.predict(input_data)

if(prediction[0]==0):
  print('Loan Reject')
else:
  print('Loan Accept')